"""create ci analysis reports table

Revision ID: 65ebcea9d4ca
Revises: e7cf7d98f7f7
Create Date: 2026-06-10 15:24:46.828308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65ebcea9d4ca'
down_revision: Union[str, Sequence[str], None] = 'e7cf7d98f7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('github_run_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=50), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('suspected_causes', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('issue_title', sa.Text(), nullable=False),
    sa.Column('issue_body', sa.Text(), nullable=False),
    sa.Column('github_issue_id', sa.BigInteger(), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.Text(), nullable=True),
    sa.Column('github_issue_state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['github_repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'github_run_id', name='uq_ci_analysis_reports_repository_run')
    )
    op.create_index(op.f('ix_ci_analysis_reports_github_run_id'), 'ci_analysis_reports', ['github_run_id'], unique=False)
    op.create_index(op.f('ix_ci_analysis_reports_id'), 'ci_analysis_reports', ['id'], unique=False)
    op.create_index(op.f('ix_ci_analysis_reports_repository_id'), 'ci_analysis_reports', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ci_analysis_reports_repository_id'), table_name='ci_analysis_reports')
    op.drop_index(op.f('ix_ci_analysis_reports_id'), table_name='ci_analysis_reports')
    op.drop_index(op.f('ix_ci_analysis_reports_github_run_id'), table_name='ci_analysis_reports')
    op.drop_table('ci_analysis_reports')
    # ### end Alembic commands ###
